<?php

/* ===========================================================================
 * Copyright 2018 Zindex Software
 * Copyright 2026 noir-framework
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ============================================================================ */

declare(strict_types=1);

namespace Noirapi\Database;

use InvalidArgumentException;
use Noirapi\Database\SQL\Expression;
use Noirapi\Database\SQL\Insert;
use Noirapi\Database\SQL\Query;
use Noirapi\Database\SQL\Update;
use PDOException;

/**
 * Entry point for queries: `$db->from('users')->where('id')->is(1)->select()`.
 */
class Database
{
    protected ?Schema $schema = null;

    public function __construct(protected Connection $connection)
    {
    }

    public function getConnection(): Connection
    {
        return $this->connection;
    }

    /**
     * @return list<array{query: string, time?: float}>
     */
    public function getLog(): array
    {
        return $this->connection->getLog();
    }

    /**
     * @param string|array<int|string, string|Expression> $tables a table, a list of tables, or table => alias
     */
    public function from(string|array $tables): Query
    {
        return new Query($this->connection, $tables);
    }

    /**
     * @param array<string, mixed> $values column => value
     */
    public function insert(array $values): Insert
    {
        return (new Insert($this->connection))->insert($values);
    }

    /**
     * Multi-row insert: `$db->insertMany([['a' => 1], ['a' => 2]])->into('t')`.
     *
     * @param list<array<string, mixed>> $rows each row is column => value, all with the same columns
     *
     * @throws InvalidArgumentException When the rows' columns differ
     */
    public function insertMany(array $rows): Insert
    {
        return (new Insert($this->connection))->insertMany($rows);
    }

    /**
     * The id generated by the last INSERT on this connection (the first one for a multi-row insert
     * on MySQL). PostgreSQL needs the sequence name.
     *
     * @throws PDOException
     */
    public function lastInsertId(?string $name = null): string|false
    {
        return $this->connection->getPDO()->lastInsertId($name);
    }

    /**
     * @param string|array<int|string, string|Expression> $table
     */
    public function update(string|array $table): Update
    {
        return new Update($this->connection, $table);
    }

    public function schema(): Schema
    {
        return $this->schema ??= $this->connection->getSchema();
    }

    /**
     * Runs the callback (receiving this Database) inside a transaction.
     *
     * @template TResult
     * @template TDefault
     *
     * @param callable(Database): TResult $query
     * @param TDefault $default
     * @param positive-int $attempts Run again after a deadlock or lock wait timeout, see Connection::transaction()
     *
     * @return TResult|TDefault
     *
     * @throws PDOException
     */
    public function transaction(callable $query, mixed $default = null, int $attempts = 1): mixed
    {
        /** @var callable(mixed): TResult $query */
        return $this->connection->transaction($query, $this, $default, $attempts);
    }
}
